name: Test action
on:
    workflow_dispatch

jobs:
    print-hello:
        runs-on: ubuntu-latest
        environment: test
        steps:
            - name: echo test text
              run: echo "Test OK ✅"
